// Code generated by "stringer -type=Hash"; DO NOT EDIT

package example

import "fmt"

const _Hash_name = "MD4MD5SHA1SHA224SHA256SHA384SHA512MD5SHA1RIPEMD160SHA3_224SHA3_256SHA3_384SHA3_512SHA512_224SHA512_256"

var _Hash_map = map[Hash]string{
	1:     _Hash_name[0:3],
	2:     _Hash_name[3:6],
	4:     _Hash_name[6:10],
	8:     _Hash_name[10:16],
	16:    _Hash_name[16:22],
	32:    _Hash_name[22:28],
	64:    _Hash_name[28:34],
	128:   _Hash_name[34:41],
	256:   _Hash_name[41:50],
	512:   _Hash_name[50:58],
	1024:  _Hash_name[58:66],
	2048:  _Hash_name[66:74],
	4096:  _Hash_name[74:82],
	8192:  _Hash_name[82:92],
	16384: _Hash_name[92:102],
}

func (i Hash) String() string {
	if str, ok := _Hash_map[i]; ok {
		return str
	}
	return fmt.Sprintf("Hash(%d)", i)
}
