// Code generated by "stringer -type=MyType"; DO NOT EDIT

package example

import "fmt"

const (
	_MyType_name_0 = "AB"
	_MyType_name_1 = "C"
	_MyType_name_2 = "D"
)

var (
	_MyType_index_0 = [...]uint8{0, 1, 2}
	_MyType_index_1 = [...]uint8{0, 1}
	_MyType_index_2 = [...]uint8{0, 1}
)

func (i MyType) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _MyType_name_0[_MyType_index_0[i]:_MyType_index_0[i+1]]
	case i == 4:
		return _MyType_name_1
	case i == 8:
		return _MyType_name_2
	default:
		return fmt.Sprintf("MyType(%d)", i)
	}
}
